@startuml Chess Class Diagram
    enum PieceKind {
        KING
        QUEEN
        ROOK
        BISHOP
        KNIGHT
        PAWN
    }

    enum Color {
        BLACK
        WHITE
    }

    abstract class Piece {
        Color color
        PieceKind type
        int id

        + boolean isWhite()
        + PieceKind getType()
        + int getId()
    }

    class King
    class Queen 
    class Rook
    class Bishop
    class Knight
    class Pawn

    class GameController

    class Game

    class Board

    class Player

    Piece <|.. King
    Piece <|.. Knight
    Piece <|.. Queen
    Piece <|.. Rook
    Piece <|.. Bishop
    Piece <|.. Pawn

@enduml